added measurement script
lifebit-ai/mlops pull request #16
Opened 2022-09-13 21:56 UTC by stefan-lifebit

**WHY**

- We need a script to evaluate our models on staging and prod.

**What?**

- Added a script for relation model evaluation

2022-09-14 13:27 UTC, ankushc48 commented on measurement_scripts/relation_measurement.py
> +                    break
Can you please explain why you needed to use `try except` here? 
Is something coming from the data? If yes, should not you make the change in data itself such that you don't have do this redundant code/computation (assuming it comes from the data) every time the measurements are done? 

If it is something else, please comment why is this required here.

2022-09-14 13:28 UTC, ankushc48 commented on measurement_scripts/relation_measurement.py
> +                continue
Instead of continuing here, should it not throw an exception? Assuming this indicates that either something is wrong with the `create_true_pred_list` or sample is faulty. If the sample is faulty why would we pass it through measurements scripts?

I would assume this is probably only useful for the new samples added to the dataset.

2022-09-14 16:06 UTC, ceru23 requested changes
Just a couple of comment, just ensure that we are only dealing with allowed relations here

2022-09-14 16:06 UTC, ceru23 commented on measurement_scripts/relation_measurement.py
> +
One thing here you should check that the relation created is allowed, that is that is in the allowed relations specified in the config.yaml file under the field "relation_types"

2022-09-14 16:06 UTC, ceru23 commented on measurement_scripts/relation_measurement.py
> +                and pred_relation["entity_2"]["tag"] == relation["entity_2"]["tag"]
to make it a bit more readable I suggest the use of a sort of "hash" function for relation, similarly to this one used in the pretrain utils file https://github.com/lifebit-ai/nlp-relation-extraction/blob/78f24a0055d7a788ab8aa3461b25f2bf4ffe9952/utils/pretrain_utils.py#L170

2022-09-15 12:54 UTC, ceru23 approved these changes
LGTM!

2022-09-15 13:16 UTC, ankushc48 requested changes
Look already quite good. Small fix still needed.

2022-09-15 13:16 UTC, ankushc48 commented on measurement_scripts/relation_measurement.py
> +        for x in true_rel
This would make relations tag order dependent due to the tuple. 

`(tag1, tag2) != (tag1, tag2)`

Which is problematic for the comparisons of labels below.

It could be a set instead of tuple but then `TAG` needs to hash function, then.

2022-09-15 13:24 UTC, ankushc48 commented on measurement_scripts/relation_measurement.py
> +                break
Same here, these comparisons assert that 

order `(tag1, tag2)` should be preserved for two relations to be equal.

2022-09-16 06:17 UTC, stefan-lifebit commented on measurement_scripts/relation_measurement.py
> +        for x in true_rel
But I always check the both way, like here with if else: https://github.com/lifebit-ai/mlops/blob/eb33bbb3b8401770a3d17248ba1324671060be2e/measurement_scripts/relation_measurement.py#L110

2022-09-16 06:37 UTC, ankushc48 commented on measurement_scripts/relation_measurement.py
> +        for x in true_rel
Right! 😮‍💨  Apologies, I missed that before. Using a set would reduce the code much though. But it's okay for now.

2022-09-16 06:38 UTC, ankushc48 approved these changes

2022-09-16 06:40 UTC, merged