Producer for sending data to SQS
lifebit-ai/mlops pull request #28
Opened 2022-09-30 13:10 UTC by stefan-lifebit

**WHY**
In order to test the whole system we first have to send data to SQS

**WHAT**
Used code from nlp-data-ingestors repo to create producer that will send data from Valohai to SQS

2022-10-03 12:40 UTC, ankushc48 commented on measurement_scripts/whole_system_evaluation/producer.py
> +from whole_system_evaluation.utils import load_configuration
Correct me if wrong, `load_configuration` is the only function used in the utils module?
 
 And it does not use rest of the functions there? Do you plan to use them later?

2022-10-04 06:24 UTC, stefan-lifebit commented on measurement_scripts/whole_system_evaluation/producer.py
> +from whole_system_evaluation.utils import load_configuration
Yes, you are right.

2022-10-04 08:14 UTC, ankushc48 commented on measurement_scripts/whole_system_evaluation/producer.py
> +from whole_system_evaluation.utils import load_configuration
Okay, then. Not sure, why should those functions be added when you really use them?

2022-10-04 08:26 UTC, stefan-lifebit commented on measurement_scripts/whole_system_evaluation/producer.py
> +from whole_system_evaluation.utils import load_configuration
I removed them, they left after copy pasting from other repo

2022-10-04 08:48 UTC, ankushc48 approved these changes
LGTM 👍. But would also recommend another approval here.

2022-10-04 15:42 UTC, rishy requested changes
Please delete the config repo and either put it in github secrets or should be loaded from private repost

2022-10-04 17:10 UTC, ericanand commented on measurement_scripts/whole_system_evaluation/config.yaml
> +diffbot_url: "http://api.diffbot.com"
I've done this - know that it's not my PR but I completely agree with Rishy that we need to be vigilant on this. No secrets please on repos!

2022-10-04 17:10 UTC, ericanand commented on measurement_scripts/whole_system_evaluation/config.yaml
> +diffbot_url: "http://api.diffbot.com"
It would be ideal if we could rebase the commits into one, to update the git history in case someone checked

2022-10-04 19:05 UTC, closed without merging